<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Items in Room</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .room-info {
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 10px;
        }
        .room-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .room-info th, .room-info td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .room-info th {
            background-color: #f5f5f5;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
            color: #666;
            padding: 10px 0;
            border-top: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Items in Room</h2>
    </div>

    <div class="room-info">
        <table>
            <tr>
                <th>Room Name</th>
                <th>Location</th>
                <th>Area (m²)</th>
            </tr>
            <tr>
                <td>{{ $room->name }}</td>
                <td>{{ $room->location->name }}</td>
                <td>{{ $room->area }}</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Item Name</th>
                <th>Category</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->item_name }}</td>
                <td>{{ $item->category->cat_name }}</td>
                <td>{{ $item->qty }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ Auth::user()->name }} | Date: {{ now()->format('d/m/Y H:i:s') }}</p>
    </div>
</body>
</html> 